### ISSUE TITLE
concolic stdin?

### ISSUE THREAD

**Issue by bannsec** [S2E/docs#21]
Following https://github.com/S2E/docs/blob/master/src/Howtos/Concolic.rst

Looking at the concolic page, it's not clear if it only works for arguments. I attempted the following to test if it would work with stdin:

```bash
echo "Hello world" | LD_PRELOAD=./s2e.so ./${TARGET} --concolic > /dev/null 2> /dev/null
```

This finished execution immediately, apparently not changing the input to concolic. I have also tried:

```bash
./s2ecmd symbwrite 16 | LD_PRELOAD=./s2e.so ./${TARGET} --concolic > /dev/null 2> /dev/null
```

But it's not clear that is doing anything other than normal symbolic.

One additional question: since you appear to put the --concolic flag inline with execution, does that mean if a program happened to take --concolic as a flag itself, one would be unable to exercise that flag? While a minor overlap, it seems that the concolic trigger from the user would be better suited in a custom environment variable, such as `S2E_CONCOLIC`. Less overlap, and also in my opinion cleaner to not muck with the program's arguments.

**Comment by Owlz** [comment]
Just seeing a reference to "seeds" here, which seems like this: https://github.com/S2E/docs/blob/16ca279d47c698df74bf8eb89d5034fd0f31b298/src/s2e-env.rst#using-seed-files

If so, that would be a good link to put into the concolic section as well.

**Comment by adrianherrera** [comment]
Hey Owlz,

That documentation is completely out of date. In fact, I thought I had
submitted a PR that removed all mentions of `--concolic` a week or so ago.
Evidently it got lost somewhere. I'll have to check my branches to see
where it got to.

The concolic flag no longer exists. Only the S2E_SYM_ARGS environment
variable.

Feel free to submit a PR for the seeds.

~Adrian

**Comment by Owlz** [comment]
Is it possible to use concolic execution approach for stdin? Looks like that's similar to "seeds".

**Comment by Owlz** [comment]
I _think_ this will do that using seeds, but not sure:

```bash
cat ${SYMB_FILE} | LD_PRELOAD=./s2e.so ./${TARGET}  > /dev/null 2> /dev/null
```

The output looks like this in debug
```
SeedSearcher: Looking for new seeds
SeedSearcher: name: 1-1.txt index:1 priority:1
SeedSearcher: Fetched 1 valid seeds
SeedSearcher:  Seeds are disabled
```

So something is disabling the seeds. The config file has:
```lua
add_plugin("SeedSearcher")
pluginsConfig.SeedSearcher = {
    enableSeeds = true,
    seedDirectory = "/home/s2e/s2e/projects/test_concolic/seeds",
}
```

**Comment by vitalych** [comment]
SeedSearcher on its own does not do anything. It provides mechanisms for SeedScheduler, which implements the actual policies. In particular, it enables/disables seed fetching depending on the current load.

Maybe we should delete the enableSeeds option altogether, it's pretty confusing.

**Comment by adrianherrera** [comment]
Do you mean just implictily "enableSeeds" by default? If so, yes, I agree.

**Comment by vitalych** [comment]
@adrianherrera  yes, enable it by default and remove the option.
